---
title: "1-modelling-processes"
output: html_document
---

```{r}
library(tidyverse)
library(rsample)
library(caret)
library(h2o)
library(readxl)
library(TSstudio)
library(plotly)

h2o.no_progress()
h2o.init()
```

```{r}
ames <- AmesHousing::make_ames()
head(ames)
```

```{r}
ames.h2o <- as.h2o(ames)
head(ames.h2o)
```

```{r}
attrition <- read_csv("/home/jeremy/Work/Data Science/Code in Zip/homlr-master/data/attrition.csv")
head(attrition)
```

```{r}
churn <- attrition %>%
  mutate_if(is.ordered, .funs = factor, ordered = FALSE)

churn.h2o <- as.h2o(churn)
head(churn.h2o)
```

### Data Splitting

#### 1. Simple Random Sampling

```{r}
set.seed(40)

# Using base R
index_1 <- sample(1:nrow(ames), round(nrow(ames) * 0.7))
train_1 <- ames[index_1, ]
test_1 <- ames[-index_1, ]

# Using caret
index_2 <- createDataPartition(ames$Sale_Price, p = 0.7, list = FALSE)
train_2 <- ames[index_2, ]
test_2 <- ames[-index_2, ]

# Using rsample
split_1 <- initial_split(ames, prop = 0.7)
train_3 <- training(split_1)
test_3 <- testing(split_1)

# Using h2o
split_2 <- h2o.splitFrame(ames.h2o, ratios = 0.7, seed = 40)
train_4 <- split_2[[1]]
test_4 <- split_2[[2]]

#Using TSstudio for time series
split_3 <- ts_split(USVSales, sample.out = 12)
train_5 <- split_3$train
test_5 <- split_3$test
```

### 2. Stratified Sampling

```{r}
table(churn$Attrition) %>% prop.table()
```

```{r}
split_strat <- initial_split(churn, prop = 0.7, strata = "Attrition")

train_strat <- training(split_strat)
test_strat <- testing(split_strat)

table(train_strat$Attrition) %>% prop.table()
```

```{r}
table(test_strat$Attrition) %>% prop.table()
```

### Resampling Methods

#### 1. k-fold cross validation

```{r}
x = c("Year_Sold", "Longitude", "Latitude")
y = c("Sale_Price")
```

```{r}
h2o.cv <- h2o.glm(
  x = x,
  y = y,
  training_frame = ames.h2o,
  nfolds = 10
)
```

```{r}
vfold_cv(ames, v = 10)
```

#### 2. Bootstrapping

```{r}
bootstraps(ames, times = 10)
```

```{r}
split <- initial_split(ames, prop = 0.7, strata = "Sale_Price")

ames_train <- training(split)
ames_test <- testing(split)
```

```{r}
# Specify resampling strategy
cv <- trainControl(
  method = "repeatedcv",
  number = 10,
  repeats = 5
)

# Create grid of hyperparameter values
hyper_grid <- expand.grid(k = seq(2, 25, by = 1))

# Tune a knn model using grid search
knn_fit <- train(
  Sale_Price ~ .,
  data = ames_train,
  method = "knn",
  trControl = cv,
  tuneGrid = hyper_grid,
  metric = "RMSE"
)

knn_fit
```

```{r}
ggplot(knn_fit)
```
