---
title: "4-logistic-regression"
output: html_document
---

```{r}
library(tidyverse)
library(caret)
library(h2o)
library(vip)
library(pdp)
library(plotly)
library(TSstudio)
library(rsample)
```

```{r}
attrition <- read_csv("/home/jeremy/Work/Data Science/Code in Zip/homlr-master/data/attrition.csv")
head(attrition)
```

```{r}
df <- attrition %>% mutate_if(is.ordered, factor, ordered = FALSE)

set.seed(40) # for reproducibility

churn_split <- initial_split(df, prop = .7, strata = "Attrition")
churn_train <- training(churn_split)
churn_test <- testing(churn_split)
```

```{r}
churn_train <- churn_train %>%
  mutate(Attrition = recode(Attrition, "Yes" = 1, "No" = 0))

churn_test <- churn_test %>%
  mutate(Attrition = recode(Attrition, "Yes" = 1, "No" = 0))
```

```{r}
head(churn_train)
head(churn_test)
```

```{r}
model1 <- glm(Attrition ~ MonthlyIncome, family = "binomial", data = churn_train)
model2 <- glm(Attrition ~ OverTime, family = "binomial", data = churn_train)
```

```{r}
tidy(model1)
tidy(model2)
```

```{r}
exp(coef(model1))
exp(coef(model2))
```

```{r}
confint(model1, level = .95)
confint(model2, level = .95)
```

```{r}
model3 <- glm(
  Attrition ~ MonthlyIncome + OverTime,
  family = "binomial",
  data = churn_train
)

tidy(model3)
```

## Assessing Model Accuracy

```{r}
cv_model1 <- train(
  Attrition ~ MonthlyIncome,
  data = churn_train,
  method = "glm",
  family = "binomial",
  trControl = trainControl(method = "cv", number = 10)
)

cv_model2 <- train(
  Attrition ~ MonthlyIncome + OverTime,
  data = churn_train,
  method = "glm",
  family = "binomial",
  trControl = trainControl(method = "cv", number = 10)
)

cv_model3 <- train(
  Attrition ~ .,
  data = churn_train,
  method = "glm",
  family = "binomial",
  trControl = trainControl(method = "cv", number = 10)
)

# extract out of sample performance measures
summary(
  resamples(
    list(
      model1 = cv_model1,
      model2 = cv_model2,
      model3 = cv_model3
    )
  )
)$statistics$Accuracy
```

```{r}
pred_class <- predict(cv_model3, churn_train)

# create confusion matrix
confusionMatrix(
  data = relevel(pred_class, ref = "Yes"),
  reference = relevel(churn_train$Attrition, ref = "Yes")
)
```

```{r}
library(ROCR)
# Compute predicted probabilities
m1_prob <- predict(cv_model1, churn_train, type = "prob")$Yes
m3_prob <- predict(cv_model3, churn_train, type = "prob")$Yes

# Compute AUC metrics for cv_model1 and cv_model3
perf1 <- prediction(m1_prob, churn_train$Attrition) %>%
  performance(measure = "tpr", x.measure = "fpr")

perf2 <- prediction(m3_prob, churn_train$Attrition) %>%
  performance(measure = "tpr", x.measure = "fpr")

# Plot ROC curves for cv_model1 and cv_model3
plot(perf1, col = "black", lty = 2)
plot(perf2, add = TRUE, col = "blue")
legend(0.8, 0.2, legend = c("cv_model1", "cv_model3"),
col = c("black", "blue"), lty = 2:1, cex = 0.6)
```

```{r}
cv_model_pls <- train(
  Attrition ~ .,
  data = churn_train,
  method = "pls",
  family = "binomial",
  trControl = trainControl(method = "cv", number = 10),
  preProcess = c("zv", "center", "scale"),
  tuneLength = 16
)
```

```{r}
cv_model_pls$bestTune
```

```{r}
ggplot(cv_model_pls)
```

```{r}
vip(cv_model3, num_features = 20)
```

```{r}
pdp::partial(cv_model3, "DailyRate", grid.resolution = 20, plot = TRUE)
```

```{r}
pdp::partial(cv_model3, "BusinessTravel", grid.resolution = 20, plot = TRUE)
```
